### ISSUE TITLE
填完表格后，仍然无法获得下载地址

### ISSUE THREAD

**Issue by wangxiao5791509** [983632847/WebUAV-3M#1]
同学您好，我试了下百度网盘的那个链接。但是填完表格后，仍然无法获得下载地址。请问该如何解决？

**Comment by 983632847** [comment]
感谢关注！数据集的下载链接已经release，填写Google Forms表单之后，通过邮件中的“查看分数”即可下载数据集，评估工具和基线结果。2022.8.1

**Comment by deepbrainme** [comment]
你好，同学，提供得百度下载“链接”已经失效，方便重新release一份么？
