### ISSUE TITLE
The Link of Baidu Pan has failed

### ISSUE THREAD

**Issue by Eric-Chen-L** [983632847/WebUAV-3M#2]
Hi,thanks for your team’s work on WeBUAV-3M. But the link of Baidu Pan has  failed. Could you please release a copy.

**Comment by Eric-Chen-L** [comment]
Link of Baidu Pan available, sorry to interrupt.

**Comment by xyl-507** [comment]
@983632847 
hello author
Thanks for your attribution. But the Link of Baidu Pan is wrong, which redirect to google pan.
Can you update the link of Baidu Pan disk? 
Thank you very much！
