### ISSUE TITLE
What's the meaning of each line in `scenario.txt` of provided dataset?

### ISSUE THREAD

**Issue by laisimiao** [983632847/WebUAV-3M#5]

**Comment by 983632847** [comment]
Each video has a "scenario.txt" file about seven scenarios defined in Section 4. The meaning of each line is as follows:
        ## UTUSC Evaluation Protocal
        self.sce_dict = {
            'Low_light': 0, 'Long-term_occlusion': 1, 'Small_targets': 2,
            'High-speed_motion': 3, 'Dual-dynamic_disturbances': 4, 'Target_distortions': 5,
            'Adversarial_examples':6}

You can find more information in the "got10k/experiments/webuav3m.py".
