### ISSUE TITLE
 Evaluation Toolkits is empty

### ISSUE THREAD

**Issue by Jasper0068** [983632847/WebUAV-3M#7]
Thank you for your excellent work! Such an important dataset to contribute to the drone tracking field. I would like to test the results of my model on your dataset, but I find that the Evaluation Tools folder is empty.

**Comment by Jasper0068** [comment]
I found it in Baidu Pan,Thanks!

**Comment by Jasper0420** [comment]
where is```
 bash UnzipWebUAV3M-Train.sh
bash UnzipWebUAV3M-Val.sh
bash UnzipWebUAV3M-Test.sh
bash UnzipWebUAV3M-AE.sh (optional)
```?

**Comment by Jasper0068** [comment]
Where are the tools down there?
```
bash UnzipWebUAV3M-Train.sh
bash UnzipWebUAV3M-Val.sh
bash UnzipWebUAV3M-Test.sh
bash UnzipWebUAV3M-AE.sh (optional)
```
