### ISSUE TITLE
When do you provide audio annotations?

### ISSUE THREAD

**Issue by Fo4me** [983632847/WebUAV-3M#8]

**Comment by 983632847** [comment]
Thank you for your attention! 

We are currently conducting the final rounds of checks and will release the audio annotations to the public in the near future (maybe a month).

**Comment by 983632847** [comment]
We have released the Audio Annotations V1.0 using a more powerful text-to-speech tool (TTS-VUE). Since we found that it can produce better audio quality than Balabolka.
