### ISSUE TITLE
labels about the superclass and a semantic label ?

### ISSUE THREAD

**Issue by ZhanYang-nwpu** [983632847/WebUAV-3M#9]
How can we get the labels of the superclass and the semantic class (target or motion class)? 
It doesn't seem to be in the current dataset.

**Comment by 983632847** [comment]
Thank you for your attention!  We have updated the superclass, object classes and motion classes in ```WebUAV-3M.xlsx```. You can download it from the official download links [Baidu Pan](https://pan.baidu.com/s/1eCdyyamoM4NZ67YeD61KCg) (UAV3) and [Google Drive](https://docs.google.com/forms/d/e/1FAIpQLSe5Usq9VUSGjKollBCI1heln_o6u4SuiMcBRn_FNqp4v2d0Kw/viewform?usp=pp_url). 

Note: Only the person superclass provides the motion classes.
